#!/usr/bin/env python3
# Copyright 2026 Honu Robotics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Generate every artifact of one tutorial USV instance from its name.

Writes into an output directory the URDF, the composed Gazebo model
(model.sdf plus model.config, so the directory works as a model:// root on
GZ_SIM_RESOURCE_PATH), the ros_gz bridge config and an RViz config, all
expanded with the same instance name, which is the model name, the prefix
of every topic, the prefix of every sensor frame and the TF prefix RViz
looks the links up under. Several boats in one simulation are several
instances with different names:

    ros2 run tutorial_usv_gazebo configure_vehicle.py --name boat_a --out-dir ~/boat_a
    ros2 launch tutorial_usv_gazebo spawn.launch.xml name:=boat_a   # does this for you

With --cache the directory is $ROS_HOME/tutorial_usv_gazebo/<name> (ROS_HOME
defaults to ~/.ros), so the same name always lands in the same place; its
path is printed and nothing else, which is how the launch file calls it.
"""

import argparse
import os
import pathlib
import re
import subprocess
import sys

from ament_index_python.packages import get_package_share_directory
import yaml

MODEL_CONFIG = """\
<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.12">model.sdf</sdf>
  <author><name>Honu Robotics</name></author>
  <description>Tutorial USV instance {name}, generated by configure_vehicle.py.</description>
</model>
"""

# A name is a Gazebo model name, a ROS namespace and a TF frame prefix at once.
NAME = re.compile(r'^[A-Za-z][A-Za-z0-9_]*$')


def run(cmd, what):
    out = subprocess.run(cmd, capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f'{what} failed ({out.returncode}):\n{out.stderr}')
    return out.stdout


def configure(name, out_dir):
    """Generate the URDF, model.sdf, model.config and bridge yaml into out_dir."""
    if not NAME.match(name):
        sys.exit(f'invalid instance name {name!r}: letters, digits and '
                 'underscores, starting with a letter')
    desc = pathlib.Path(get_package_share_directory('tutorial_usv_description'))
    gz = pathlib.Path(get_package_share_directory('tutorial_usv_gazebo'))
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # The URDF carries no instance name; robot_state_publisher's frame_prefix
    # adds it in TF. Expanded here rather than copied so a source checkout
    # and an installed package behave the same.
    urdf = out_dir / 'tutorial_usv.urdf'
    urdf.write_text(run(['xacro', str(desc / 'urdf' / 'tutorial_usv.urdf.xacro')],
                        'URDF generation'))
    sdf = out_dir / 'model.sdf'
    sdf.write_text(run(['xacro', str(gz / 'model.sdf.xacro'),
                        f'name:={name}', f'urdf_uri:=file://{urdf}'],
                       'model generation'))
    (out_dir / 'model.config').write_text(MODEL_CONFIG.format(name=name))
    template = (gz / 'config' / 'ros_gz_bridge.yaml.in').read_text()
    (out_dir / 'ros_gz_bridge.yaml').write_text(template.replace('@name@', name))
    (out_dir / 'tutorial_usv.rviz').write_text(
        rviz_config((desc / 'rviz' / 'tutorial_usv.rviz').read_text(), name))
    return out_dir


def rviz_config(text, name):
    """
    Return the description's RViz config, pointed at one instance.

    In a simulation every TF frame carries the instance name and the
    description is published in its namespace, so RViz needs the fixed frame
    and the description topic of that instance, and the RobotModel display's
    TF Prefix, without which it looks the links up under their bare URDF
    names and draws nothing.
    """
    config = yaml.safe_load(text)
    manager = config['Visualization Manager']
    manager['Global Options']['Fixed Frame'] = f'{name}/base_link'
    manager['Views']['Current']['Target Frame'] = f'{name}/base_link'
    for display in manager['Displays']:
        if display.get('Class') == 'rviz_default_plugins/RobotModel':
            display['TF Prefix'] = name
            display['Description Topic']['Value'] = f'/{name}/robot_description'
    return yaml.safe_dump(config, sort_keys=False)


def cache_dir(name):
    """Per instance directory under $ROS_HOME."""
    ros_home = pathlib.Path(os.environ.get('ROS_HOME', pathlib.Path.home() / '.ros'))
    return ros_home / 'tutorial_usv_gazebo' / name


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--name', default='tutorial_usv',
                    help='instance name: model name, topic and frame prefix')
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument('--out-dir', help='directory to write the artifacts into')
    group.add_argument('--cache', action='store_true',
                       help='write into $ROS_HOME/tutorial_usv_gazebo/<name>, print its path')
    args = ap.parse_args(argv)

    out_dir = cache_dir(args.name) if args.cache else args.out_dir
    configure(args.name, out_dir)
    if args.cache:
        sys.stdout.write(str(out_dir))
    else:
        print(f'wrote tutorial_usv.urdf, model.sdf, model.config, '
              f'ros_gz_bridge.yaml and tutorial_usv.rviz for {args.name} to {out_dir}')


if __name__ == '__main__':
    main()
